### ISSUE TITLE
Bad links in the api admin

### ISSUE THREAD

**Issue by philipobrien** [OPENi-ict/api-framework#53]
The documentation link doesn't work

![image](https://cloud.githubusercontent.com/assets/1763813/8523109/3e5de4de-23eb-11e5-9176-e076cc0dab01.png)

**Comment by mpetyx** [comment]
this is just empty.
since the static files are not displayed well (due to some mongrel issue), buttons are not there.
So, if you would like to register a new account, if you go to the apiadmin/ just press add.
otherwise, you can create accounts by following the link, apiadmin/socialaccount/socialtoken/add/
